namespace Teto.Companion;

internal static class Program
{
    /// <summary>
    /// Entry point. [STAThread] is required by Windows Forms: UI components
    /// (and COM objects they use) expect a single-threaded apartment.
    /// </summary>
    [STAThread]
    private static void Main(string[] args)
    {
        var pipeName = args.Length > 0 ? args[0] : PipeListener.DefaultName;

        // A named mutex makes the app single-instance per user session:
        // a second copy finds the mutex already owned and exits.
        using var single = new Mutex(initiallyOwned: true, @"Local\TetoCompanion", out var first);
        if (!first)
        {
            return;
        }

        ApplicationConfiguration.Initialize(); // DPI awareness, visual styles (generated by the SDK)
        using var app = new TrayApp(pipeName);
        Application.Run(app);
    }
}
